# Generated by Django 5.1.6 on 2026-06-10 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('comando', models.JSONField(default=list)),
                ('comando_trabajo', models.JSONField(blank=True, default=list)),
                ('endpoint_url', models.CharField(blank=True, help_text='URL base de un Ollama (ej: http://localhost:11434). Vacío = silla CLI.', max_length=200)),
                ('endpoint_model', models.CharField(blank=True, help_text='Nombre del modelo en el endpoint (ej: qwen2.5:3b).', max_length=100)),
                ('permitir_consulta', models.BooleanField(default=False, help_text='Si el rango consulta puede usar esta silla. False = solo control.')),
                ('color', models.CharField(blank=True, help_text='Código ANSI para el REPL.', max_length=20)),
                ('persona', models.TextField(blank=True, help_text='Encuadre de rol/estilo (variante A, rango control). Va ARRIBA del prompt.')),
                ('persona_consulta', models.TextField(blank=True, help_text='Persona variante B para rango consulta. Vacío = usa la A.')),
                ('recordatorio', models.TextField(blank=True, help_text='Se repite ABAJO del prompt (recencia).')),
                ('especialidad', models.CharField(blank=True, help_text='Capacidad corta para que el líder reparta mejor (ej: "frontend/CSS", "scripts/automatización", "redacción"). Vacío = sin pista.', max_length=120)),
                ('rol', models.CharField(choices=[('trabajador', 'Trabajador'), ('lider', 'Líder')], default='trabajador', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['orden', 'key'],
            },
        ),
        migrations.CreateModel(
            name='WakeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('solicitante', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'ordering': ['creado_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkerRestart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('solicitante', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'ordering': ['creado_at'],
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Mesa', max_length=200)),
                ('topologia', models.CharField(choices=[('plana', 'Plana (broadcast)'), ('lider', 'Líder')], default='plana', max_length=20)),
                ('rondas', models.PositiveIntegerField(default=2)),
                ('timeout', models.PositiveIntegerField(default=180, help_text='Segundos por call a un CLI.')),
                ('activa', models.BooleanField(default=True)),
                ('fijada', models.BooleanField(default=False)),
                ('detener_solicitado', models.BooleanField(default=False)),
                ('continuo', models.BooleanField(default=False)),
                ('objetivo', models.TextField(blank=True, help_text='Objetivo del modo continuo (lo fija /continuo).')),
                ('costo_tope', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('auto', models.BooleanField(default=False)),
                ('auto_iter', models.PositiveIntegerField(default=0)),
                ('ultimo_humano_respondido', models.PositiveIntegerField(default=0)),
                ('workspace_dir', models.CharField(blank=True, help_text='Carpeta de trabajo PERSISTENTE de la mesa (host abs path). La setea el worker al primer fabricar en modo scratch. Vacío = todavía no se fabricó ahí.', max_length=500)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('creador', models.ForeignKey(blank=True, help_text='Quién creó la mesa. control ve todas; consulta solo las suyas.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enjambre_sesiones', to=settings.AUTH_USER_MODEL)),
                ('lider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_lideradas', to='enjambre.participante')),
                ('participantes', models.ManyToManyField(blank=True, help_text='Sillas que participan en esta mesa. Vacío = todas las activas.', related_name='sesiones', to='enjambre.participante')),
            ],
            options={
                'ordering': ['-creado_at'],
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emisor', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('es_ruido', models.BooleanField(default=False)),
                ('es_sistema', models.BooleanField(default=False)),
                ('tokens', models.PositiveIntegerField(default=0)),
                ('costo', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('participante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes', to='enjambre.participante')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='enjambre.sesion')),
            ],
            options={
                'ordering': ['creado_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='LogMesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('info', 'Info'), ('paso', 'Paso'), ('ok', 'OK'), ('error', 'Error')], default='info', max_length=10)),
                ('texto', models.CharField(max_length=500)),
                ('detalle', models.TextField(blank=True)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='enjambre.sesion')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('ordenes', models.TextField(help_text='Las instrucciones para el agente (el briefing).')),
                ('repo_path', models.CharField(blank=True, help_text='Repo git destino en disco (modo repo). Vacío = modo scratch (carpeta de la mesa).', max_length=500)),
                ('persistente', models.BooleanField(default=False, help_text='True = fabrica IN-PLACE en la carpeta persistente de la mesa (scratch), sin worktree efímero; las tareas se acumulan.')),
                ('base_ref', models.CharField(default='HEAD', help_text='Ref desde donde ramificar (modo repo).', max_length=200)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En curso'), ('hecha', 'Hecha'), ('sin_cambios', 'Sin cambios'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('salida', models.TextField(blank=True, help_text='Última salida del agente.')),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('actualizado_at', models.DateTimeField(auto_now=True)),
                ('participante', models.ForeignKey(blank=True, help_text='La silla que ejecuta. SET_NULL: si se borra la silla, la Tarea queda HUÉRFANA (participante nulo) para que el Líder la reasigne, en vez de bloquear el borrado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='enjambre.participante')),
                ('sesion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='enjambre.sesion')),
            ],
            options={
                'ordering': ['-creado_at'],
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='Ruta del worktree en disco.', max_length=500)),
                ('branch', models.CharField(help_text='Branch aislado (enjambre/...).', max_length=200)),
                ('base_commit', models.CharField(blank=True, max_length=64)),
                ('commit_sha', models.CharField(blank=True, help_text='Commit del resultado, si hubo.', max_length=64)),
                ('estado', models.CharField(choices=[('creado', 'Creado'), ('comiteado', 'Comiteado'), ('limpiado', 'Limpiado')], default='creado', max_length=20)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('tarea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workspace', to='enjambre.tarea')),
            ],
        ),
    ]
