# Generated by Django 5.1.6 on 2026-06-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enjambre', '0002_seed_sillas_ejemplo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WakeRequest',
        ),
        migrations.AlterField(
            model_name='participante',
            name='endpoint_url',
            field=models.CharField(blank=True, help_text='URL base de un Ollama (ej: http://localhost:11434). Vacío = silla CLI.', max_length=200),
        ),
    ]
