# Generated by Django 5.1.6 on 2026-07-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enjambre', '0003_delete_wakerequest_alter_participante_endpoint_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvataresEnjambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultron', models.TextField(blank=True, help_text='Retrato 1:1 de la voz orquestadora (reservado), data-URI.')),
                ('enjambre', models.TextField(blank=True, help_text='Retrato 1:1 del Enjambre (mensajes de sistema), data-URI.')),
                ('humano', models.TextField(blank=True, help_text='Retrato 1:1 del humano, data-URI.')),
                ('color_ultron', models.CharField(blank=True, help_text='Color de la voz orquestadora (hex). Vacío = negro.', max_length=9)),
                ('color_enjambre', models.CharField(blank=True, help_text='Color del Enjambre (hex). Vacío = negro.', max_length=9)),
                ('color_humano', models.CharField(blank=True, help_text='Color del humano (hex). Vacío = negro.', max_length=9)),
            ],
        ),
        migrations.AddField(
            model_name='participante',
            name='avatar',
            field=models.TextField(blank=True, help_text='Retrato 1:1 como data-URI. Vacío = usa el punto de color.'),
        ),
        migrations.AddField(
            model_name='participante',
            name='color_ui',
            field=models.CharField(blank=True, help_text='Color en la mesa (hex #rrggbb). Vacío = negro.', max_length=9),
        ),
        migrations.AddField(
            model_name='participante',
            name='rol_tarjeta',
            field=models.CharField(blank=True, default='', help_text='Rol corto para la tarjeta del panel (ej: "Arquitecto", "Red Team"). Solo display — NO se pasa a las sillas ni al contexto.', max_length=40),
        ),
    ]
