# Generated by Django 5.1.6 on 2026-07-14 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enjambre', '0004_avataresenjambre_participante_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emisor', models.CharField(blank=True, help_text='Nombre de la silla (snapshot).', max_length=100)),
                ('herramienta', models.CharField(help_text='inspect|read_file|list_dir|system_report|apply_fix', max_length=30)),
                ('es_mutacion', models.BooleanField(default=False)),
                ('comando', models.TextField(help_text='Comando/ruta que la silla quiso correr.')),
                ('motivo', models.TextField(blank=True, help_text='Por qué (lo explica la silla en apply_fix).')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de aprobación'), ('ejecutada', 'Ejecutada'), ('rechazada', 'Rechazada'), ('error', 'Error')], default='ejecutada', max_length=12)),
                ('salida', models.TextField(blank=True, help_text='Salida (stdout/stderr) o razón del rechazo.')),
                ('aprobada_por', models.CharField(blank=True, max_length=150)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('resuelto_at', models.DateTimeField(blank=True, help_text='Cuándo se aprobó/rechazó/ejecutó.', null=True)),
                ('participante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones', to='enjambre.participante')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones', to='enjambre.sesion')),
            ],
            options={
                'ordering': ['-creado_at', '-id'],
            },
        ),
    ]
