# Generated by Django 5.1.6 on 2026-07-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enjambre', '0008_retirar_chispa'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='confinar',
            field=models.BooleanField(default=True, help_text='Las sillas trabajan en la carpeta de la mesa salvo que se pida otra ruta.'),
        ),
    ]
