# Generated by Django 5.1.6 on 2026-09-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enjambre', '0009_sesion_confinar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='participantes',
            field=models.ManyToManyField(blank=True, help_text='Sillas que participan en esta mesa. Vacío = ninguna (mesa muda).', related_name='sesiones', to='enjambre.participante'),
        ),
    ]
